export const countries = [
  { code: "IN", name: "India", flag: "https://flagcdn.com/w20/in.png", dialCode: "+91", pattern: /^[6-9]\d{9}$/ },
  { code: "US", name: "United States", flag: "https://flagcdn.com/w20/us.png", dialCode: "+1", pattern: /^\d{10}$/ },
  { code: "GB", name: "United Kingdom", flag: "https://flagcdn.com/w20/gb.png", dialCode: "+44", pattern: /^\d{10,11}$/ },
  { code: "AU", name: "Australia", flag: "https://flagcdn.com/w20/au.png", dialCode: "+61", pattern: /^\d{9}$/ },
  { code: "CA", name: "Canada", flag: "https://flagcdn.com/w20/ca.png", dialCode: "+1", pattern: /^\d{10}$/ },
  { code: "AE", name: "UAE", flag: "https://flagcdn.com/w20/ae.png", dialCode: "+971", pattern: /^\d{8,9}$/ },
  { code: "SG", name: "Singapore", flag: "https://flagcdn.com/w20/sg.png", dialCode: "+65", pattern: /^\d{8}$/ },
  { code: "DE", name: "Germany", flag: "https://flagcdn.com/w20/de.png", dialCode: "+49", pattern: /^\d{10,12}$/ },
  { code: "FR", name: "France", flag: "https://flagcdn.com/w20/fr.png", dialCode: "+33", pattern: /^\d{9,10}$/ },
  { code: "IT", name: "Italy", flag: "https://flagcdn.com/w20/it.png", dialCode: "+39", pattern: /^\d{9,11}$/ },
  { code: "ES", name: "Spain", flag: "https://flagcdn.com/w20/es.png", dialCode: "+34", pattern: /^\d{9}$/ },
  { code: "NL", name: "Netherlands", flag: "https://flagcdn.com/w20/nl.png", dialCode: "+31", pattern: /^\d{9}$/ },
  { code: "BE", name: "Belgium", flag: "https://flagcdn.com/w20/be.png", dialCode: "+32", pattern: /^\d{8,9}$/ },
  { code: "CH", name: "Switzerland", flag: "https://flagcdn.com/w20/ch.png", dialCode: "+41", pattern: /^\d{9}$/ },
  { code: "AT", name: "Austria", flag: "https://flagcdn.com/w20/at.png", dialCode: "+43", pattern: /^\d{10,12}$/ },
  { code: "SE", name: "Sweden", flag: "https://flagcdn.com/w20/se.png", dialCode: "+46", pattern: /^\d{8,9}$/ },
  { code: "NO", name: "Norway", flag: "https://flagcdn.com/w20/no.png", dialCode: "+47", pattern: /^\d{8}$/ },
  { code: "DK", name: "Denmark", flag: "https://flagcdn.com/w20/dk.png", dialCode: "+45", pattern: /^\d{8}$/ },
  { code: "FI", name: "Finland", flag: "https://flagcdn.com/w20/fi.png", dialCode: "+358", pattern: /^\d{8,9}$/ },
  { code: "PL", name: "Poland", flag: "https://flagcdn.com/w20/pl.png", dialCode: "+48", pattern: /^\d{9}$/ },
  { code: "CZ", name: "Czech Republic", flag: "https://flagcdn.com/w20/cz.png", dialCode: "+420", pattern: /^\d{9}$/ },
  { code: "HU", name: "Hungary", flag: "https://flagcdn.com/w20/hu.png", dialCode: "+36", pattern: /^\d{8,9}$/ },
  { code: "RO", name: "Romania", flag: "https://flagcdn.com/w20/ro.png", dialCode: "+40", pattern: /^\d{9}$/ },
  { code: "BG", name: "Bulgaria", flag: "https://flagcdn.com/w20/bg.png", dialCode: "+359", pattern: /^\d{8,9}$/ },
  { code: "GR", name: "Greece", flag: "https://flagcdn.com/w20/gr.png", dialCode: "+30", pattern: /^\d{10}$/ },
  { code: "PT", name: "Portugal", flag: "https://flagcdn.com/w20/pt.png", dialCode: "+351", pattern: /^\d{9}$/ },
  { code: "IE", name: "Ireland", flag: "https://flagcdn.com/w20/ie.png", dialCode: "+353", pattern: /^\d{8,9}$/ },
  { code: "LU", name: "Luxembourg", flag: "https://flagcdn.com/w20/lu.png", dialCode: "+352", pattern: /^\d{6,11}$/ },
  { code: "MT", name: "Malta", flag: "https://flagcdn.com/w20/mt.png", dialCode: "+356", pattern: /^\d{8}$/ },
  { code: "CY", name: "Cyprus", flag: "https://flagcdn.com/w20/cy.png", dialCode: "+357", pattern: /^\d{8}$/ },
  { code: "EE", name: "Estonia", flag: "https://flagcdn.com/w20/ee.png", dialCode: "+372", pattern: /^\d{7,8}$/ },
  { code: "LV", name: "Latvia", flag: "https://flagcdn.com/w20/lv.png", dialCode: "+371", pattern: /^\d{8}$/ },
  { code: "LT", name: "Lithuania", flag: "https://flagcdn.com/w20/lt.png", dialCode: "+370", pattern: /^\d{8}$/ },
  { code: "SI", name: "Slovenia", flag: "https://flagcdn.com/w20/si.png", dialCode: "+386", pattern: /^\d{8}$/ },
  { code: "SK", name: "Slovakia", flag: "https://flagcdn.com/w20/sk.png", dialCode: "+421", pattern: /^\d{9}$/ },
  { code: "HR", name: "Croatia", flag: "https://flagcdn.com/w20/hr.png", dialCode: "+385", pattern: /^\d{8,9}$/ },
  { code: "RS", name: "Serbia", flag: "https://flagcdn.com/w20/rs.png", dialCode: "+381", pattern: /^\d{8,9}$/ },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/w20/ba.png", dialCode: "+387", pattern: /^\d{8}$/ },
  { code: "MK", name: "North Macedonia", flag: "https://flagcdn.com/w20/mk.png", dialCode: "+389", pattern: /^\d{8}$/ },
  { code: "AL", name: "Albania", flag: "https://flagcdn.com/w20/al.png", dialCode: "+355", pattern: /^\d{8,9}$/ },
  { code: "ME", name: "Montenegro", flag: "https://flagcdn.com/w20/me.png", dialCode: "+382", pattern: /^\d{8}$/ },
  { code: "RU", name: "Russia", flag: "https://flagcdn.com/w20/ru.png", dialCode: "+7", pattern: /^\d{10}$/ },
  { code: "UA", name: "Ukraine", flag: "https://flagcdn.com/w20/ua.png", dialCode: "+380", pattern: /^\d{9}$/ },
  { code: "BY", name: "Belarus", flag: "https://flagcdn.com/w20/by.png", dialCode: "+375", pattern: /^\d{9}$/ },
  { code: "MD", name: "Moldova", flag: "https://flagcdn.com/w20/md.png", dialCode: "+373", pattern: /^\d{8}$/ },
  { code: "GE", name: "Georgia", flag: "https://flagcdn.com/w20/ge.png", dialCode: "+995", pattern: /^\d{9}$/ },
  { code: "AM", name: "Armenia", flag: "https://flagcdn.com/w20/am.png", dialCode: "+374", pattern: /^\d{8}$/ },
  { code: "AZ", name: "Azerbaijan", flag: "https://flagcdn.com/w20/az.png", dialCode: "+994", pattern: /^\d{9}$/ },
  { code: "KZ", name: "Kazakhstan", flag: "https://flagcdn.com/w20/kz.png", dialCode: "+7", pattern: /^\d{10}$/ },
  { code: "UZ", name: "Uzbekistan", flag: "https://flagcdn.com/w20/uz.png", dialCode: "+998", pattern: /^\d{9}$/ },
  { code: "KG", name: "Kyrgyzstan", flag: "https://flagcdn.com/w20/kg.png", dialCode: "+996", pattern: /^\d{9}$/ },
  { code: "TJ", name: "Tajikistan", flag: "https://flagcdn.com/w20/tj.png", dialCode: "+992", pattern: /^\d{9}$/ },
  { code: "TM", name: "Turkmenistan", flag: "https://flagcdn.com/w20/tm.png", dialCode: "+993", pattern: /^\d{8}$/ },
  { code: "CN", name: "China", flag: "https://flagcdn.com/w20/cn.png", dialCode: "+86", pattern: /^\d{11}$/ },
  { code: "JP", name: "Japan", flag: "https://flagcdn.com/w20/jp.png", dialCode: "+81", pattern: /^\d{10,11}$/ },
  { code: "KR", name: "South Korea", flag: "https://flagcdn.com/w20/kr.png", dialCode: "+82", pattern: /^\d{9,10}$/ },
  { code: "TW", name: "Taiwan", flag: "https://flagcdn.com/w20/tw.png", dialCode: "+886", pattern: /^\d{9}$/ },
  { code: "HK", name: "Hong Kong", flag: "https://flagcdn.com/w20/hk.png", dialCode: "+852", pattern: /^\d{8}$/ },
  { code: "MO", name: "Macau", flag: "https://flagcdn.com/w20/mo.png", dialCode: "+853", pattern: /^\d{8}$/ },
  { code: "MY", name: "Malaysia", flag: "https://flagcdn.com/w20/my.png", dialCode: "+60", pattern: /^\d{9,10}$/ },
  { code: "TH", name: "Thailand", flag: "https://flagcdn.com/w20/th.png", dialCode: "+66", pattern: /^\d{9}$/ },
  { code: "VN", name: "Vietnam", flag: "https://flagcdn.com/w20/vn.png", dialCode: "+84", pattern: /^\d{9,10}$/ },
  { code: "PH", name: "Philippines", flag: "https://flagcdn.com/w20/ph.png", dialCode: "+63", pattern: /^\d{10}$/ },
  { code: "ID", name: "Indonesia", flag: "https://flagcdn.com/w20/id.png", dialCode: "+62", pattern: /^\d{9,12}$/ },
  { code: "BN", name: "Brunei", flag: "https://flagcdn.com/w20/bn.png", dialCode: "+673", pattern: /^\d{7}$/ },
  { code: "KH", name: "Cambodia", flag: "https://flagcdn.com/w20/kh.png", dialCode: "+855", pattern: /^\d{8,9}$/ },
  { code: "LA", name: "Laos", flag: "https://flagcdn.com/w20/la.png", dialCode: "+856", pattern: /^\d{8,9}$/ },
  { code: "MM", name: "Myanmar", flag: "https://flagcdn.com/w20/mm.png", dialCode: "+95", pattern: /^\d{8,10}$/ },
  { code: "BD", name: "Bangladesh", flag: "https://flagcdn.com/w20/bd.png", dialCode: "+880", pattern: /^\d{10}$/ },
  { code: "PK", name: "Pakistan", flag: "https://flagcdn.com/w20/pk.png", dialCode: "+92", pattern: /^\d{10}$/ },
  { code: "LK", name: "Sri Lanka", flag: "https://flagcdn.com/w20/lk.png", dialCode: "+94", pattern: /^\d{9}$/ },
  { code: "MV", name: "Maldives", flag: "https://flagcdn.com/w20/mv.png", dialCode: "+960", pattern: /^\d{7}$/ },
  { code: "NP", name: "Nepal", flag: "https://flagcdn.com/w20/np.png", dialCode: "+977", pattern: /^\d{10}$/ },
  { code: "BT", name: "Bhutan", flag: "https://flagcdn.com/w20/bt.png", dialCode: "+975", pattern: /^\d{8}$/ },
  { code: "AF", name: "Afghanistan", flag: "https://flagcdn.com/w20/af.png", dialCode: "+93", pattern: /^\d{9}$/ },
  { code: "IR", name: "Iran", flag: "https://flagcdn.com/w20/ir.png", dialCode: "+98", pattern: /^\d{10}$/ },
  { code: "IQ", name: "Iraq", flag: "https://flagcdn.com/w20/iq.png", dialCode: "+964", pattern: /^\d{10}$/ },
  { code: "SA", name: "Saudi Arabia", flag: "https://flagcdn.com/w20/sa.png", dialCode: "+966", pattern: /^\d{9}$/ },
  { code: "KW", name: "Kuwait", flag: "https://flagcdn.com/w20/kw.png", dialCode: "+965", pattern: /^\d{8}$/ },
  { code: "QA", name: "Qatar", flag: "https://flagcdn.com/w20/qa.png", dialCode: "+974", pattern: /^\d{8}$/ },
  { code: "BH", name: "Bahrain", flag: "https://flagcdn.com/w20/bh.png", dialCode: "+973", pattern: /^\d{8}$/ },
  { code: "OM", name: "Oman", flag: "https://flagcdn.com/w20/om.png", dialCode: "+968", pattern: /^\d{8}$/ },
  { code: "YE", name: "Yemen", flag: "https://flagcdn.com/w20/ye.png", dialCode: "+967", pattern: /^\d{9}$/ },
  { code: "JO", name: "Jordan", flag: "https://flagcdn.com/w20/jo.png", dialCode: "+962", pattern: /^\d{9}$/ },
  { code: "LB", name: "Lebanon", flag: "https://flagcdn.com/w20/lb.png", dialCode: "+961", pattern: /^\d{7,8}$/ },
  { code: "SY", name: "Syria", flag: "https://flagcdn.com/w20/sy.png", dialCode: "+963", pattern: /^\d{8,9}$/ },
  { code: "IL", name: "Israel", flag: "https://flagcdn.com/w20/il.png", dialCode: "+972", pattern: /^\d{9}$/ },
  { code: "PS", name: "Palestine", flag: "https://flagcdn.com/w20/ps.png", dialCode: "+970", pattern: /^\d{9}$/ },
  { code: "TR", name: "Turkey", flag: "https://flagcdn.com/w20/tr.png", dialCode: "+90", pattern: /^\d{10}$/ },
  { code: "EG", name: "Egypt", flag: "https://flagcdn.com/w20/eg.png", dialCode: "+20", pattern: /^\d{10}$/ },
  { code: "LY", name: "Libya", flag: "https://flagcdn.com/w20/ly.png", dialCode: "+218", pattern: /^\d{9}$/ },
  { code: "TN", name: "Tunisia", flag: "https://flagcdn.com/w20/tn.png", dialCode: "+216", pattern: /^\d{8}$/ },
  { code: "DZ", name: "Algeria", flag: "https://flagcdn.com/w20/dz.png", dialCode: "+213", pattern: /^\d{9}$/ },
  { code: "MA", name: "Morocco", flag: "https://flagcdn.com/w20/ma.png", dialCode: "+212", pattern: /^\d{9}$/ },
  { code: "SD", name: "Sudan", flag: "https://flagcdn.com/w20/sd.png", dialCode: "+249", pattern: /^\d{9}$/ },
  { code: "ET", name: "Ethiopia", flag: "https://flagcdn.com/w20/et.png", dialCode: "+251", pattern: /^\d{9}$/ },
  { code: "KE", name: "Kenya", flag: "https://flagcdn.com/w20/ke.png", dialCode: "+254", pattern: /^\d{9}$/ },
  { code: "UG", name: "Uganda", flag: "https://flagcdn.com/w20/ug.png", dialCode: "+256", pattern: /^\d{9}$/ },
  { code: "TZ", name: "Tanzania", flag: "https://flagcdn.com/w20/tz.png", dialCode: "+255", pattern: /^\d{9}$/ },
  { code: "RW", name: "Rwanda", flag: "https://flagcdn.com/w20/rw.png", dialCode: "+250", pattern: /^\d{9}$/ },
  { code: "BI", name: "Burundi", flag: "https://flagcdn.com/w20/bi.png", dialCode: "+257", pattern: /^\d{8}$/ },
  { code: "DJ", name: "Djibouti", flag: "https://flagcdn.com/w20/dj.png", dialCode: "+253", pattern: /^\d{8}$/ },
  { code: "SO", name: "Somalia", flag: "https://flagcdn.com/w20/so.png", dialCode: "+252", pattern: /^\d{8,9}$/ },
  { code: "ER", name: "Eritrea", flag: "https://flagcdn.com/w20/er.png", dialCode: "+291", pattern: /^\d{7}$/ },
  { code: "ZA", name: "South Africa", flag: "https://flagcdn.com/w20/za.png", dialCode: "+27", pattern: /^\d{9}$/ },
  { code: "NA", name: "Namibia", flag: "https://flagcdn.com/w20/na.png", dialCode: "+264", pattern: /^\d{8,9}$/ },
  { code: "BW", name: "Botswana", flag: "https://flagcdn.com/w20/bw.png", dialCode: "+267", pattern: /^\d{8}$/ },
  { code: "ZW", name: "Zimbabwe", flag: "https://flagcdn.com/w20/zw.png", dialCode: "+263", pattern: /^\d{9}$/ },
  { code: "ZM", name: "Zambia", flag: "https://flagcdn.com/w20/zm.png", dialCode: "+260", pattern: /^\d{9}$/ },
  { code: "MW", name: "Malawi", flag: "https://flagcdn.com/w20/mw.png", dialCode: "+265", pattern: /^\d{8,9}$/ },
  { code: "MZ", name: "Mozambique", flag: "https://flagcdn.com/w20/mz.png", dialCode: "+258", pattern: /^\d{9}$/ },
  { code: "MG", name: "Madagascar", flag: "https://flagcdn.com/w20/mg.png", dialCode: "+261", pattern: /^\d{9}$/ },
  { code: "MU", name: "Mauritius", flag: "https://flagcdn.com/w20/mu.png", dialCode: "+230", pattern: /^\d{8}$/ },
  { code: "SC", name: "Seychelles", flag: "https://flagcdn.com/w20/sc.png", dialCode: "+248", pattern: /^\d{7}$/ },
  { code: "KM", name: "Comoros", flag: "https://flagcdn.com/w20/km.png", dialCode: "+269", pattern: /^\d{7}$/ },
  { code: "NG", name: "Nigeria", flag: "https://flagcdn.com/w20/ng.png", dialCode: "+234", pattern: /^\d{10}$/ },
  { code: "GH", name: "Ghana", flag: "https://flagcdn.com/w20/gh.png", dialCode: "+233", pattern: /^\d{9}$/ },
  { code: "CI", name: "Ivory Coast", flag: "https://flagcdn.com/w20/ci.png", dialCode: "+225", pattern: /^\d{8}$/ },
  { code: "SN", name: "Senegal", flag: "https://flagcdn.com/w20/sn.png", dialCode: "+221", pattern: /^\d{9}$/ },
  { code: "ML", name: "Mali", flag: "https://flagcdn.com/w20/ml.png", dialCode: "+223", pattern: /^\d{8}$/ },
  { code: "BF", name: "Burkina Faso", flag: "https://flagcdn.com/w20/bf.png", dialCode: "+226", pattern: /^\d{8}$/ },
  { code: "NE", name: "Niger", flag: "https://flagcdn.com/w20/ne.png", dialCode: "+227", pattern: /^\d{8}$/ },
  { code: "TD", name: "Chad", flag: "https://flagcdn.com/w20/td.png", dialCode: "+235", pattern: /^\d{8}$/ },
  { code: "CF", name: "Central African Republic", flag: "https://flagcdn.com/w20/cf.png", dialCode: "+236", pattern: /^\d{8}$/ },
  { code: "CM", name: "Cameroon", flag: "https://flagcdn.com/w20/cm.png", dialCode: "+237", pattern: /^\d{8,9}$/ },
  { code: "GQ", name: "Equatorial Guinea", flag: "https://flagcdn.com/w20/gq.png", dialCode: "+240", pattern: /^\d{9}$/ },
  { code: "GA", name: "Gabon", flag: "https://flagcdn.com/w20/ga.png", dialCode: "+241", pattern: /^\d{8}$/ },
  { code: "CG", name: "Republic of the Congo", flag: "https://flagcdn.com/w20/cg.png", dialCode: "+242", pattern: /^\d{9}$/ },
  { code: "CD", name: "Democratic Republic of the Congo", flag: "https://flagcdn.com/w20/cd.png", dialCode: "+243", pattern: /^\d{9}$/ },
  { code: "AO", name: "Angola", flag: "https://flagcdn.com/w20/ao.png", dialCode: "+244", pattern: /^\d{9}$/ },
  { code: "GW", name: "Guinea-Bissau", flag: "https://flagcdn.com/w20/gw.png", dialCode: "+245", pattern: /^\d{7}$/ },
  { code: "CV", name: "Cape Verde", flag: "https://flagcdn.com/w20/cv.png", dialCode: "+238", pattern: /^\d{7}$/ },
  { code: "ST", name: "São Tomé and Príncipe", flag: "https://flagcdn.com/w20/st.png", dialCode: "+239", pattern: /^\d{7}$/ },
  { code: "GN", name: "Guinea", flag: "https://flagcdn.com/w20/gn.png", dialCode: "+224", pattern: /^\d{8,9}$/ },
  { code: "SL", name: "Sierra Leone", flag: "https://flagcdn.com/w20/sl.png", dialCode: "+232", pattern: /^\d{8}$/ },
  { code: "LR", name: "Liberia", flag: "https://flagcdn.com/w20/lr.png", dialCode: "+231", pattern: /^\d{8}$/ },
  { code: "GM", name: "Gambia", flag: "https://flagcdn.com/w20/gm.png", dialCode: "+220", pattern: /^\d{7}$/ },
  { code: "MX", name: "Mexico", flag: "https://flagcdn.com/w20/mx.png", dialCode: "+52", pattern: /^\d{10}$/ },
  { code: "GT", name: "Guatemala", flag: "https://flagcdn.com/w20/gt.png", dialCode: "+502", pattern: /^\d{8}$/ },
  { code: "BZ", name: "Belize", flag: "https://flagcdn.com/w20/bz.png", dialCode: "+501", pattern: /^\d{7}$/ },
  { code: "SV", name: "El Salvador", flag: "https://flagcdn.com/w20/sv.png", dialCode: "+503", pattern: /^\d{8}$/ },
  { code: "HN", name: "Honduras", flag: "https://flagcdn.com/w20/hn.png", dialCode: "+504", pattern: /^\d{8}$/ },
  { code: "NI", name: "Nicaragua", flag: "https://flagcdn.com/w20/ni.png", dialCode: "+505", pattern: /^\d{8}$/ },
  { code: "CR", name: "Costa Rica", flag: "https://flagcdn.com/w20/cr.png", dialCode: "+506", pattern: /^\d{8}$/ },
  { code: "PA", name: "Panama", flag: "https://flagcdn.com/w20/pa.png", dialCode: "+507", pattern: /^\d{8}$/ },
  { code: "CU", name: "Cuba", flag: "https://flagcdn.com/w20/cu.png", dialCode: "+53", pattern: /^\d{8}$/ },
  { code: "JM", name: "Jamaica", flag: "https://flagcdn.com/w20/jm.png", dialCode: "+1876", pattern: /^\d{7}$/ },
  { code: "HT", name: "Haiti", flag: "https://flagcdn.com/w20/ht.png", dialCode: "+509", pattern: /^\d{8}$/ },
  { code: "DO", name: "Dominican Republic", flag: "https://flagcdn.com/w20/do.png", dialCode: "+1809", pattern: /^\d{7}$/ },
  { code: "PR", name: "Puerto Rico", flag: "https://flagcdn.com/w20/pr.png", dialCode: "+1787", pattern: /^\d{7}$/ },
  { code: "TT", name: "Trinidad and Tobago", flag: "https://flagcdn.com/w20/tt.png", dialCode: "+1868", pattern: /^\d{7}$/ },
  { code: "BB", name: "Barbados", flag: "https://flagcdn.com/w20/bb.png", dialCode: "+1246", pattern: /^\d{7}$/ },
  { code: "GD", name: "Grenada", flag: "https://flagcdn.com/w20/gd.png", dialCode: "+1473", pattern: /^\d{7}$/ },
  { code: "LC", name: "Saint Lucia", flag: "https://flagcdn.com/w20/lc.png", dialCode: "+1758", pattern: /^\d{7}$/ },
  { code: "VC", name: "Saint Vincent and the Grenadines", flag: "https://flagcdn.com/w20/vc.png", dialCode: "+1784", pattern: /^\d{7}$/ },
  { code: "AG", name: "Antigua and Barbuda", flag: "https://flagcdn.com/w20/ag.png", dialCode: "+1268", pattern: /^\d{7}$/ },
  { code: "DM", name: "Dominica", flag: "https://flagcdn.com/w20/dm.png", dialCode: "+1767", pattern: /^\d{7}$/ },
  { code: "KN", name: "Saint Kitts and Nevis", flag: "https://flagcdn.com/w20/kn.png", dialCode: "+1869", pattern: /^\d{7}$/ },
  { code: "BS", name: "Bahamas", flag: "https://flagcdn.com/w20/bs.png", dialCode: "+1242", pattern: /^\d{7}$/ },
  { code: "BM", name: "Bermuda", flag: "https://flagcdn.com/w20/bm.png", dialCode: "+1441", pattern: /^\d{7}$/ },
  { code: "AR", name: "Argentina", flag: "https://flagcdn.com/w20/ar.png", dialCode: "+54", pattern: /^\d{10,11}$/ },
  { code: "BR", name: "Brazil", flag: "https://flagcdn.com/w20/br.png", dialCode: "+55", pattern: /^\d{10,11}$/ },
  { code: "CL", name: "Chile", flag: "https://flagcdn.com/w20/cl.png", dialCode: "+56", pattern: /^\d{9}$/ },
  { code: "CO", name: "Colombia", flag: "https://flagcdn.com/w20/co.png", dialCode: "+57", pattern: /^\d{10}$/ },
  { code: "PE", name: "Peru", flag: "https://flagcdn.com/w20/pe.png", dialCode: "+51", pattern: /^\d{9}$/ },
  { code: "VE", name: "Venezuela", flag: "https://flagcdn.com/w20/ve.png", dialCode: "+58", pattern: /^\d{10}$/ },
  { code: "EC", name: "Ecuador", flag: "https://flagcdn.com/w20/ec.png", dialCode: "+593", pattern: /^\d{8,9}$/ },
  { code: "BO", name: "Bolivia", flag: "https://flagcdn.com/w20/bo.png", dialCode: "+591", pattern: /^\d{8}$/ },
  { code: "PY", name: "Paraguay", flag: "https://flagcdn.com/w20/py.png", dialCode: "+595", pattern: /^\d{9}$/ },
  { code: "UY", name: "Uruguay", flag: "https://flagcdn.com/w20/uy.png", dialCode: "+598", pattern: /^\d{8}$/ },
  { code: "GY", name: "Guyana", flag: "https://flagcdn.com/w20/gy.png", dialCode: "+592", pattern: /^\d{7}$/ },
  { code: "SR", name: "Suriname", flag: "https://flagcdn.com/w20/sr.png", dialCode: "+597", pattern: /^\d{7}$/ },
  { code: "GF", name: "French Guiana", flag: "https://flagcdn.com/w20/gf.png", dialCode: "+594", pattern: /^\d{9}$/ },
  { code: "FK", name: "Falkland Islands", flag: "https://flagcdn.com/w20/fk.png", dialCode: "+500", pattern: /^\d{5}$/ },
  { code: "NZ", name: "New Zealand", flag: "https://flagcdn.com/w20/nz.png", dialCode: "+64", pattern: /^\d{8,9}$/ },
  { code: "FJ", name: "Fiji", flag: "https://flagcdn.com/w20/fj.png", dialCode: "+679", pattern: /^\d{7}$/ },
  { code: "PG", name: "Papua New Guinea", flag: "https://flagcdn.com/w20/pg.png", dialCode: "+675", pattern: /^\d{8}$/ },
  { code: "SB", name: "Solomon Islands", flag: "https://flagcdn.com/w20/sb.png", dialCode: "+677", pattern: /^\d{7}$/ },
  { code: "VU", name: "Vanuatu", flag: "https://flagcdn.com/w20/vu.png", dialCode: "+678", pattern: /^\d{7}$/ },
  { code: "NC", name: "New Caledonia", flag: "https://flagcdn.com/w20/nc.png", dialCode: "+687", pattern: /^\d{6}$/ },
  { code: "PF", name: "French Polynesia", flag: "https://flagcdn.com/w20/pf.png", dialCode: "+689", pattern: /^\d{8}$/ },
  { code: "TO", name: "Tonga", flag: "https://flagcdn.com/w20/to.png", dialCode: "+676", pattern: /^\d{5}$/ },
  { code: "WS", name: "Samoa", flag: "https://flagcdn.com/w20/ws.png", dialCode: "+685", pattern: /^\d{7}$/ },
  { code: "KI", name: "Kiribati", flag: "https://flagcdn.com/w20/ki.png", dialCode: "+686", pattern: /^\d{8}$/ },
  { code: "PW", name: "Palau", flag: "https://flagcdn.com/w20/pw.png", dialCode: "+680", pattern: /^\d{7}$/ },
  { code: "NR", name: "Nauru", flag: "https://flagcdn.com/w20/nr.png", dialCode: "+674", pattern: /^\d{7}$/ },
  { code: "FM", name: "Micronesia", flag: "https://flagcdn.com/w20/fm.png", dialCode: "+691", pattern: /^\d{7}$/ },
  { code: "MH", name: "Marshall Islands", flag: "https://flagcdn.com/w20/mh.png", dialCode: "+692", pattern: /^\d{7}$/ },
  { code: "TV", name: "Tuvalu", flag: "https://flagcdn.com/w20/tv.png", dialCode: "+688", pattern: /^\d{6}$/ },
]
