#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Running code style checks'
# Check Prettier standards
yarn check-format ||
(
    echo 'Prettier Check Failed. Run yarn format, add changes and try commit again.';
    false;
)
echo '\n';

echo 'Running Next lint check'
# Check Next lint Standards
yarn lint ||
(
    echo 'Next lint Check Failed. Make the required changes listed above, add changes and try to commit again.'
    false; 
)
echo '\n';

echo 'Running typescript check'
# Check tsconfig standards
yarn code-check ||
(
    echo 'Typescript check failed'
    false;
)
echo '\n';

# If everything passes... Now we can commit
echo 'Trying to build now.'
yarn build ||
(
    echo 'Next build failed!'
    false;
)

echo 'Everything is good. Committing now.'npm test









